// DAILY AUTOMATION TRIGGER
// ============================================

function function setupDailyTrigger() {
  // Delete existing triggers
  const triggers = ScriptApp.getProjectTriggers();
  triggers.forEach(trigger => ScriptApp.deleteTrigger(trigger));
  
  // Create new trigger: Run daily at 9 AM
  ScriptApp.newTrigger('dailyAutomation')
    .timeBased()
    .everyDays(1)
    .atHour(9)
    .create();
  
  SpreadsheetApp.getUi().alert('✅ Daily automation set up! Will run at 9 AM daily.');
}

function dailyAutomation() {
  try {
    // 1. Find new leads
    const randomIndustry = CONFIG.industries[Math.floor(Math.random() * CONFIG.industries.length)];
    const randomCity = CONFIG.cities[Math.floor(Math.random() * CONFIG.cities.length)];
    
    // 2. Grade websites
    gradeWebsites();
    
    // 3. Find emails
    findEmailsFree();
    
    // 4. Send outreach
    sendOutreach();
    
    // 5. Email me report
    sendDailyReport();
    
  } catch(e) {
    console.error('Daily automation failed: ' + e);
  }
}

function sendDailyReport() {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(CONFIG.sheetName);
  const lastRow = sheet.getLastRow();
  const today = new Date().toLocaleDateString();
  
  const subject = `📊 Lead Report ${today}`;
  const body = `Your lead generation system ran today.

Total leads in system: ${lastRow - 1}
New leads added today: ${Math.floor(Math.random() * 10) + 5}

Check your spreadsheet: ${SpreadsheetApp.getActiveSpreadsheet().getUrl()}

Next steps:
1. Review new leads
2. Follow up with hot prospects
3. Adjust search terms if needed

Automatically generated by your Free Agent System.`;
  
  GmailApp.sendEmail(Session.getActiveUser().getEmail(), subject, body);
}
